(((name . "procedure-arity")
  (signature lambda ((procedure? proc)) (or #f integer? arity-at-least? list?))
  (desc . "Produces an arity object representing the arity of proc. If this procedure produces #f, no information is available for proc."))
 ((name . "arity-at-least?")
  (signature lambda (obj) boolean?)
  (desc . "Returns #t if obj is an arity-at-least object and false otherwise."))
 ((name . "arity-at-least-value")
  (signature lambda ((arity-at-least? arity-at-least)) integer?)
  (desc . "Returns the exact non-negative integer denoting the minimum number of arguments required by the given arity-at-least object."))
 ((name . "procedure-arity-includes?")
  (signature lambda ((procedure? proc) (integer? k)) boolean?)
  (desc . "Returns #t if the proc can accept k arguments and #f otherwise. If this procedure returns #f, applying proc to k arguments will result in an arity error.")))
